### ISSUE TITLE
hello bro can i use ur project and make some changes to the UI we have the same project for MSD

### ISSUE THREAD

**Issue by Zhuang-Zixian** [bennygdev/foodsnap-v1#1]

**Comment by bennygdev** [comment]
Hey you definitely can. But you do not have to use all my features, just meet the required features can already. If you need any help you can provide your discord or email

**Comment by Zhuang-Zixian** [comment]
my discord is bixi_ im not sure how the code works but ima try to change it so it doesn't look like yours if not Mr Anthony gonna kill me AHAHAHAHA

**Comment by Zhuang-Zixian** [comment]
btw i have met u before for PPD2 we are APW students

**Comment by bennygdev** [comment]
Ok will add u once im back
